services:
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: gotok
  #     POSTGRES_USER: gotok
  #     POSTGRES_PASSWORD: gotok
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U gotok"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  gotok-1:
    build: .
    environment:
      GOTOK_DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/gotok?sslmode=disable
      GOTOK_REDIS_ADDR: host.docker.internal:6379
      GOTOK_DATA_DIR: /app/data
      GOTOK_LISTEN_ADDR: ":8080"
    ports:
      - "8080:8080"
    volumes:
      - uploads1:/app/data/uploads
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_healthy

  gotok-2:
    build: .
    environment:
      GOTOK_DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/gotok?sslmode=disable
      GOTOK_REDIS_ADDR: host.docker.internal:6379
      GOTOK_DATA_DIR: /app/data
      GOTOK_LISTEN_ADDR: ":8080"
    ports:
      - "8081:8080"
    volumes:
      - uploads2:/app/data/uploads
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata:
  uploads1:
  uploads2:
